#!/usr/bin/env sh

echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./packages/styled-components/.npmrc

git config user.email "continuous.integration@intellihr.com.au"
git config user.name "IntelliHR CI"

git remote add github "git@github.com:intellihr/styled-components.git" || true
git checkout master

yarn run publish

git push --tags github
git push github HEAD:master
